<?php

return [
    'modules' => [
        'dashboard' => [
            'label' => 'Dashboard',
            'permission' => 'dashboard.view',
            'description' => 'High-level dashboard visibility and summary alerts.',
        ],
        'setup' => [
            'label' => 'Factory / Floor / Line Setup',
            'permission' => 'setup.view',
            'description' => 'Setup master visibility for factory structure and support references.',
        ],
        'machine-master' => [
            'label' => 'Machine Master',
            'permission' => 'machine-master.view',
            'description' => 'Machine list, details, and master-data visibility.',
        ],
        'rent-machines' => [
            'label' => 'Rent Machines',
            'permission' => 'rent-machines.view',
            'description' => 'Rent machine visibility for current and future backend modules.',
        ],
        'vendors' => [
            'label' => 'Vendors',
            'permission' => 'vendors.view',
            'description' => 'Vendor record visibility and support reference access.',
        ],
        'agreements' => [
            'label' => 'Agreements',
            'permission' => 'agreements.view',
            'description' => 'Agreement review visibility and validity access.',
        ],
        'allocation' => [
            'label' => 'Allocation / Transfer',
            'permission' => 'allocation.view',
            'description' => 'Allocation and transfer visibility foundation.',
        ],
        'return-replace' => [
            'label' => 'Return / Replace',
            'permission' => 'return-replace.view',
            'description' => 'Return and replacement request visibility foundation.',
        ],
        'breakdown' => [
            'label' => 'Breakdown',
            'permission' => 'breakdown.view',
            'description' => 'Breakdown list, review, and later workflow route protection.',
        ],
        'pm' => [
            'label' => 'Preventive Maintenance',
            'permission' => 'pm.view',
            'description' => 'PM schedule, due list, and summary visibility foundation.',
        ],
        'technician-tasks' => [
            'label' => 'Technician Tasks',
            'permission' => 'technician-tasks.view',
            'description' => 'Technician task board visibility for later execution flows.',
        ],
        'spare-parts' => [
            'label' => 'Spare Parts',
            'permission' => 'spare-parts.view',
            'description' => 'Spare master and stock visibility foundation.',
        ],
        'users-access' => [
            'label' => 'Users & Access',
            'permission' => 'users.view',
            'description' => 'User, role, and permission management access foundation.',
        ],
        'approval' => [
            'label' => 'Approval Queue',
            'permission' => 'approval.view',
            'description' => 'Approval visibility foundation for later workflow control.',
        ],
        'reports' => [
            'label' => 'Reports',
            'permission' => 'reports.view',
            'description' => 'Report viewing and later export control foundation.',
        ],
    ],

    'permission_slugs' => [
        'dashboard.view',
        'machine-master.view',
        'machine-master.create',
        'machine-master.update',
        'breakdown.view',
        'breakdown.create',
        'breakdown.assign',
        'breakdown.update',
        'breakdown.close',
        'breakdown.review',
        'pm.view',
        'pm.plan',
        'pm.execute',
        'pm.complete',
        'pm.review',
        'spare-parts.view',
        'spare-parts.create',
        'spare-parts.update',
        'spare-parts.post',
        'reports.view',
        'reports.export',
        'vendors.view',
        'vendors.create',
        'vendors.update',
        'agreements.view',
        'agreements.create',
        'agreements.update',
        'rent-machines.view',
        'rent-machines.receive',
        'rent-machines.update',
        'allocation.view',
        'allocation.create',
        'return-replace.view',
        'return-replace.create',
        'return-replace.review',
        'approval.view',
        'approval.approve',
        'setup.view',
        'setup.create',
        'setup.update',
        'users.view',
        'users.create',
        'users.update',
        'users.approve',
        'technician-tasks.view',
        'technician-tasks.update',
    ],
];
